title: Leonardo Labarca # your name (or website title) here
logo: "/images/leolab.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br>Here you can explore some of my data analysis i've made<br>
 
  <br><br>
  <a href="linkedin.com/in/leonardo-labarca-quinonez">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
